- name: set CDH5 ubuntu repo
  get_url:
      url: 'https://archive.cloudera.com/cdh5/ubuntu/xenial/amd64/cdh/cloudera.list'
      dest: '/etc/apt/sources.list.d/cloudera.list'

- apt_key:
    url: "https://archive.cloudera.com/cdh5/ubuntu/xenial/amd64/cdh/archive.key"
    state: present

- name: add priority to the CDH5
  blockinfile:
        path: /etc/apt/preferences.d/cloudera.pref
        create: yes
        block: |
            Package: *
            Pin: release o=Cloudera, l=Cloudera
            Pin-Priority: 501

- name: set bigtop-utils repo
  get_url:
      url: 'https://archive.apache.org/dist/bigtop/bigtop-1.2.0/repos/ubuntu16.04/bigtop.list'
      dest: '/etc/apt/sources.list.d/bigtop-1.2.0.list'

- apt_key:
    url: "http://archive.apache.org/dist/bigtop/bigtop-1.2.0/repos/GPG-KEY-bigtop"
    state: present

- name: Run the equivalent of apt-get update as a separate step
  apt:
    update_cache: yes

- name: install packages
  tags: packages
  apt: name={{item}} state=latest
  with_items:
    - "{{ java_package }}"
    - bigtop-utils

- name: install template configurations
  tags: config
  template: src={{ item }}.j2 dest=/etc/default/{{ item }}
  with_items:
    - bigtop-utils

- name: create directories
  tags: config
  # is this a 'dirname' or just regex_replace? dirname would just strip '/' off the end
  file: path="{{ item | regex_replace('[^/]+/*$','') }}" state=directory owner=root group=root mode=755 follow=yes
  with_items:
    - "{{ zookeeper_data_dir }}"
    - "{{ log_folder }}"
    - "{{ etc_folder }}"

- name: generate services.xml
  tags:
    - config
    - clinit
  local_action: template src="services.xml.j2" dest={{ inventory_dir }}/workdir/services.xml
  run_once: true

- name: generate interfaces index
  tags:
    - config
    - interfaces
  local_action: template src="interfaces.j2" dest={{ inventory_dir }}/workdir/interfaces
  run_once: true

